### ISSUE TITLE
Integration test doesn't work

### ISSUE THREAD

**Issue by oleksii-frolov** [ConnectSDK/Connect-SDK-Android-API-Sampler_IntegrationTest#1]
Please make sure that integration test project is compiled with the latest Sampler app. Also I suggest such things:
- rename robotium folder into libs
- add build.gradle for supporting default IDE - Android Studio

**Comment by ashikachhabda** [comment]
Checkedin the dependent files in Sampler Code for sdk-1.5 also renamed robotiun with libs

**Comment by oleksii-frolov** [comment]
Ok, now it's compiled and run
